# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
workflows:
  version: 2
  test:
    jobs:
      - test-3.6:
          filters:
            tags:
              only: /.*/
      - test-3.5:
          filters:
            tags:
              only: /.*/
      - test-2.7:
          filters:
            tags:
              only: /.*/
      - deploy:
          requires:
            - test-3.6
            - test-3.5
            - test-2.7
          filters:
            tags:
              only: /[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
jobs:
  test-3.6: &test-template
    docker:
      - image: circleci/python:3.6.1
    working_directory: ~/opentmi-pyclient
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            python --version
            python -m venv venv || virtualenv venv
            echo activate
            . venv/bin/activate
            pip install -r requirements.txt
            pip install -r dev_requirements.txt
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      # run tests!
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            coverage run setup.py test
            coverage html
            coveralls || true
            pylint opentmi_client
      - store_artifacts:
          path: htmlcov
          destination: htmlcov

  test-3.5:
    <<: *test-template
    docker:
      - image: circleci/python:3.5-jessie

  test-2.7:
    <<: *test-template
    docker:
      - image: python:2.7.13

  deploy:
    <<: *test-template
    steps:
      - run:
          name: verify git tag vs. version
          command: |
            . venv/bin/activate
            python setup.py verify
      - run:
          name: init .pypirc
          command: |
            echo -e "[pypi]" >> ~/.pypirc
            echo -e "username = $PYPI_USERNAME" >> ~/.pypirc
            echo -e "password = $PYPI_PASSWORD" >> ~/.pypirc
      - run:
          name: create packages
          command: |
            python setup.py sdist
            python setup.py bdist_wheel
      - run:
          name: upload to pypi
          command: |
            . venv/bin/activate
            twine upload --repository-url https://test.pypi.org/legacy/ dist/*
