version: 2
jobs:
  build:
    working_directory: ~/opentmi-pyclient
    docker:
      - image: circleci/python:3.6.1
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "setup-py" }}
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "setup.py" }}
          paths:
            - "venv"
      - run:
          command: |
            . venv/bin/activate
            python setup.py test
      - store_artifacts:
          path: test-reports/
          destination: tr1
